-- Create Tokens Table
CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number INT NOT NULL,
    customer_name TEXT,
    phone_number TEXT,
    email TEXT,
    service_type TEXT,
    source TEXT,
    status TEXT DEFAULT 'Waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    remarks TEXT
);

-- Create Settings Table
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Insert Default Settings
INSERT INTO settings (key, value) VALUES
    ('Starting Token Number', '100'),
    ('Last Generated Token', '100'),
    ('Current Serving Token', '0'),
    ('Average Service Time', '10'),
    ('Organization Name', 'Smart Token Management System'),
    ('Enable Buzzer', 'true'),
    ('Thermal Printer Settings', 'Default'),
    ('Admin Password', 'admin123');

-- Enable RLS on tables
ALTER TABLE tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

-- Create policies for tokens table
CREATE POLICY "Allow anon read access on tokens" ON tokens FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert access on tokens" ON tokens FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Allow anon update access on tokens" ON tokens FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Allow anon delete access on tokens" ON tokens FOR DELETE TO anon USING (true);

-- Create policies for settings table
CREATE POLICY "Allow anon read access on settings" ON settings FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon update access on settings" ON settings FOR UPDATE TO anon USING (true) WITH CHECK (true);
