-- Create Tokens Table
CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_number INT NOT NULL,
    customer_name TEXT,
    phone_number TEXT,
    email TEXT,
    service_type TEXT,
    source TEXT,
    status TEXT DEFAULT 'Waiting',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    remarks TEXT
);

-- Create Settings Table
CREATE TABLE settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- Insert Default Settings
INSERT INTO settings (key, value) VALUES
    ('Starting Token Number', '100'),
    ('Last Generated Token', '100'),
    ('Current Serving Token', '0'),
    ('Average Service Time', '10'),
    ('Organization Name', 'Smart Token Management System'),
    ('Enable Buzzer', 'true'),
    ('Thermal Printer Settings', 'Default'),
    ('Admin Password', 'admin123');
